import 'dart:ui';

import 'package:filmica/features/presets/preset_model.dart';

class PresetData {
  PresetData._();

  static const List<String> categories = [
    'All',
    'Film',
    'Vintage',
    'Instant',
    'Video',
    'Effects',
  ];

  static const List<PresetConfig> allPresets = [
    // ── Primary Photo Cameras ──
    PresetConfig(
      id: 'cpm35',
      name: 'CPM35',
      category: 'Film',
      description: 'Canon Sure Shot 85 inspired. Soft romantic pastels.',
      iconName: 'camera_alt',
      warmth: 0.3,
      grain: 0.12,
      fadeAmount: 0.12,
      contrast: 1.08,
      saturation: 0.88,
      vignetteStrength: 0.18,
      redShift: 0.06,
      halation: 0.15,
      vignetteRadius: 0.6,
    ),
    PresetConfig(
      id: 'd_classic',
      name: 'D Classic',
      category: 'Vintage',
      description: 'Lomography toy camera. Vibrant shifts, heavy vignette.',
      iconName: 'filter_vintage',
      saturation: 1.35,
      contrast: 1.25,
      vignetteStrength: 0.5,
      warmth: 0.2,
      grain: 0.22,
      redShift: 0.08,
      greenShift: -0.04,
      vignetteRadius: 0.4,
      halation: 0.1,
    ),
    PresetConfig(
      id: 'classic_s',
      name: 'Classic S',
      category: 'Film',
      description: 'Hipstamatic-style. High contrast, stylized light leaks.',
      iconName: 'photo_camera',
      isPremium: true,
      individualPrice: 1.49,
      contrast: 1.3,
      saturation: 1.15,
      warmth: 0.2,
      grain: 0.15,
      vignetteStrength: 0.2,
      halation: 0.2,
      redShift: 0.04,
      overlayAsset: 'assets/overlays/light_leak.png',
      overlayOpacity: 0.3,
    ),
    PresetConfig(
      id: 'inst_sq',
      name: 'Inst SQ',
      category: 'Instant',
      description: 'Square Instax instant film frame.',
      iconName: 'crop_square',
      warmth: 0.22,
      grain: 0.08,
      fadeAmount: 0.18,
      contrast: 1.05,
      saturation: 0.92,
      brightness: 0.06,
      borderWidth: 0.08,
      borderColor: Color(0xFFF5F0E8),
    ),
    PresetConfig(
      id: 'inst_mini',
      name: 'Inst Mini',
      category: 'Instant',
      description: 'Fujifilm Instax Mini 90 polaroid look.',
      iconName: 'photo',
      isPremium: true,
      individualPrice: 1.49,
      warmth: 0.18,
      grain: 0.1,
      fadeAmount: 0.22,
      contrast: 1.05,
      saturation: 1.0,
      brightness: 0.08,
      borderWidth: 0.06,
      borderColor: Color(0xFFFFFFFF),
      halation: 0.1,
    ),
    PresetConfig(
      id: 'ct2',
      name: 'CT2',
      category: 'Film',
      description: 'Cross-processed slide film look.',
      iconName: 'gradient',
      isPremium: true,
      individualPrice: 0.99,
      saturation: 1.4,
      contrast: 1.25,
      warmth: -0.2,
      grain: 0.15,
      vignetteStrength: 0.22,
      greenShift: 0.12,
      blueShift: -0.08,
      redShift: -0.05,
      vignetteRadius: 0.45,
    ),
    PresetConfig(
      id: 'half_1',
      name: 'Half 1',
      category: 'Film',
      description: 'Konica Recorder half-frame diptych feel.',
      iconName: 'view_column',
      isPremium: true,
      individualPrice: 1.49,
      contrast: 1.12,
      saturation: 0.88,
      warmth: 0.12,
      grain: 0.2,
      fadeAmount: 0.1,
      vignetteStrength: 0.25,
      effectType: 'half_frame',
    ),

    // ── Vintage & Toy Cameras ──
    PresetConfig(
      id: 'd_fun_s',
      name: 'D Fun S',
      category: 'Vintage',
      description: 'Kodak Fun Saver disposable camera look.',
      iconName: 'photo_camera_front',
      warmth: 0.4,
      grain: 0.38,
      fadeAmount: 0.15,
      contrast: 1.18,
      saturation: 1.2,
      vignetteStrength: 0.4,
      redShift: 0.1,
      halation: 0.12,
      vignetteRadius: 0.35,
    ),
    PresetConfig(
      id: 'fuji_s',
      name: 'Fuji S',
      category: 'Vintage',
      description: 'Fuji Simple Ace disposable inspired.',
      iconName: 'camera',
      isPremium: true,
      individualPrice: 0.99,
      warmth: 0.15,
      grain: 0.28,
      fadeAmount: 0.15,
      contrast: 1.1,
      saturation: 1.05,
      vignetteStrength: 0.32,
      greenShift: 0.06,
      blueShift: 0.03,
      vignetteRadius: 0.4,
    ),
    PresetConfig(
      id: 'hoga',
      name: 'Hoga',
      category: 'Vintage',
      description: 'Holga plastic lens. Edge blur, light leaks.',
      iconName: 'blur_on',
      isPremium: true,
      individualPrice: 1.49,
      contrast: 1.08,
      saturation: 1.15,
      warmth: 0.28,
      grain: 0.3,
      vignetteStrength: 0.6,
      edgeSoftness: 0.7,
      halation: 0.2,
      vignetteRadius: 0.3,
      overlayAsset: 'assets/overlays/light_leak.png',
      overlayOpacity: 0.25,
    ),
    PresetConfig(
      id: 'grd_r',
      name: 'GRD R',
      category: 'Film',
      description: 'Ricoh GR inspired. Grainy high-contrast B&W.',
      iconName: 'monochrome_photos',
      isPremium: true,
      individualPrice: 1.49,
      saturation: 0.0,
      contrast: 1.55,
      grain: 0.45,
      vignetteStrength: 0.2,
      warmth: 0.05,
      greenShift: 0.03,
      vignetteRadius: 0.5,
    ),

    // ── Classic Video Cameras ──
    PresetConfig(
      id: 'dcr',
      name: 'DCR',
      category: 'Video',
      description: '1980s VHS tape recorder. Glitches, grain, date stamp.',
      iconName: 'videocam',
      warmth: 0.08,
      grain: 0.5,
      fadeAmount: 0.28,
      contrast: 0.88,
      saturation: 0.75,
      vignetteStrength: 0.15,
      scanlines: 0.6,
      chromaShift: 0.3,
      flickerAmount: 0.15,
      redShift: 0.05,
      blueShift: -0.05,
    ),
    PresetConfig(
      id: 'c_72',
      name: 'C-72',
      category: 'Video',
      description: 'Retro 1970s Super-8 film look.',
      iconName: 'movie',
      isPremium: true,
      individualPrice: 1.49,
      warmth: 0.45,
      grain: 0.4,
      fadeAmount: 0.32,
      contrast: 1.08,
      saturation: 0.82,
      vignetteStrength: 0.38,
      halation: 0.25,
      flickerAmount: 0.08,
      vignetteRadius: 0.35,
      redShift: 0.08,
    ),

    // ── Lens Add-ons & Effects ──
    PresetConfig(
      id: 'fisheye',
      name: 'Fisheye',
      category: 'Effects',
      description: 'Extreme wide-angle fisheye effect.',
      iconName: 'panorama_fish_eye',
      isPremium: true,
      individualPrice: 0.99,
      contrast: 1.08,
      saturation: 1.12,
      vignetteStrength: 0.65,
      effectType: 'fisheye',
      vignetteRadius: 0.25,
      chromaShift: 0.15,
    ),
    PresetConfig(
      id: 'double_exp',
      name: 'Double Exposure',
      category: 'Effects',
      description: 'Overlay ghosting, double image effect.',
      iconName: 'filter',
      isPremium: true,
      individualPrice: 1.49,
      fadeAmount: 0.12,
      contrast: 1.08,
      saturation: 1.08,
      effectType: 'double_exposure',
      halation: 0.15,
      overlayOpacity: 0.45,
    ),
  ];

  static PresetConfig? getById(String id) {
    try {
      return allPresets.firstWhere((p) => p.id == id);
    } catch (_) {
      return null;
    }
  }

  static List<PresetConfig> get freePresets =>
      allPresets.where((p) => !p.isPremium).toList();

  static List<PresetConfig> get premiumPresets =>
      allPresets.where((p) => p.isPremium).toList();

  static List<PresetConfig> getByCategory(String category) {
    if (category == 'All') return allPresets;
    return allPresets.where((p) => p.category == category).toList();
  }
}
